package com.inferris.server;

public enum JedisChannels {
    PLAYERDATA_UPDATE,
    PLAYERDATA_JOIN,
    PLAYERDATA_VANISH,
    PROXY_TO_SPIGOT_PLAYERDATA_CACHE_UPDATE,
    SPIGOT_TO_PROXY_PLAYERDATA_CACHE_UPDATE,
    TEST;
}
