# config.yml

#######################################################
#                                                     #
#             Inferris Configuration                  #
#                                                     #
#######################################################

command:
  features:
    message-joke: true

friends:
  page-size: 20

test:
  value: true

internal-lockdown: false