name: Inferris
main: com.inferris.Inferris
version: 1.0
author: Refrizor

commands:
  config:
    description: Reload
  bungeetest:
    description: Test
  message:
    description: Message a player
  reply:
    description: Reply to a player
  vanish:
    description: Vanish
  alerte:
    description: Alerte
  alright:
    description: Alright
  alright2:
    description: Alright2
  rank:
    description: Set rank for a player
  coins:
    description: Set coins for a player
  channel:
    description: Set channel
  profile:
    description: Set or view profile for a player
  account:
    description: Account
  serverstate:
    description: Server state command
  report:
    description: Report command
  viewlogs:
    description: View logs
  locate:
    description: Locate a player
  friend:
    description: Friends
  resync:
    description: Admin command
  shout:
    description: Alert, but without the prefix
  buy:
    description: Buy
  permissions:
    description: List permissions
  verify:
    description: Verify your forum account
  unlink:
    description: Unlink forum account