name: Inferris
main: com.inferris.Inferris
version: 1.0
author: [Refrizor]

commands:
  config:
    description: Reload
  bungeetest:
    description: Test
  message:
    description: Message a player
  reply:
    description: Reply to a player
  vanish:
    description: Vanish
  alerte:
    description: Alerte
  alright:
    description: Alright
  alright2:
    description: Alright2